uncaughtException: no longer exit(1)
to investigate an ongoing issue on Windows, we will logger.critical but temporarily no longer exit on a uncaughtException